aa

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -147,6 +147,13 @@ jobs:
       - name: Convert plan to JSON
         run: terraform show -json tfplan.binary > tfplan.json
 
+      - name: Validate tfplan.json
+        run: |
+          if ! jq empty tfplan.json; then
+            echo "Invalid or empty tfplan.json"
+            exit 1
+          fi
+
       - name: Run terraform-compliance in Docker
         run: |
           docker run --rm \
